"""Add project members many-to-many relationship

Revision ID: 297dc083222a
Revises: fb9fbba8e2f0
Create Date: 2025-04-24 17:26:26.601403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297dc083222a'
down_revision = 'fb9fbba8e2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    # ### end Alembic commands ###
